NBCampArchive/Sikmogil

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil/Presentation/Example/View/ViewController.swift
- Sikmogil/Utills/Extensions/UIViewExtensions.swift
- Sikmogil/Utills/Helpers/DateHelper.swift
- Sikmogil/Views/CustomViews/CircularProgressBar.swift
- Sikmogil/Views/CustomViews/CustomCircularProgressBar.swift
- Extension, CustomView 추가
- Resolved: #2 #3
> Main Branch 최신화

- Sikmogil.xcodeproj/project.pbxproj
- 잃어버린 StepView 찾아오기
- 머지하다가 오류나서 찾아왔습니다
- Resolved: #
> [Fix] 잃어버린 StepView 찾아오기

- Sikmogil.xcodeproj/project.pbxproj
Reverts NBCampArchive/Sikmogil#22
> Revert "[Fix] diet proj 파일 추가"

- Sikmogil.xcodeproj/project.pbxproj
- 잃어버린 Diet 찾기
- PR Conflict Error 수정
- Resolved: #24
> [Fix] 잃어버린 Diet 찾기

- Sikmogil.xcodeproj/project.pbxproj
- Add missing Utills File
- Resolved: #26
> [Fix] 사라진 Utills 하위 파일 추가

- Sikmogil/Application/SceneDelegate.swift
- Sikmogil/Model/LoginModel.swift
- Sikmogil/Presentation/Login/View/LoginViewController.swift
- Sikmogil/Presentation/Login/ViewModel/LoginViewModel.swift
- Sikmogil/Services/Network/LoginAPIManager.swift
- Sikmogil/Services/Network/UserAPIManager.swift
- 매 로그인 마다 불필요한 온보딩 삭제
- 로그인이 유효하면 다시 로그인 하는 불필요성 검토
- 로그인 토큰 유효에 따른 RootView 변경 - SceneDelegate
- 첫 로그인 체크 - LoginModel, LoginAPIManager
- 첫 로그인 여부에 따른 화면 전환 - LoginViewModel, LoginViewController
- 401 Error 대응 토큰 재발급 - LoginAPIManager, UserAPIManager
- Resolved: #20
> [Feat] 로그인 로직 고도화

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil/Model/DietModel.swift
- Sikmogil/Model/ExerciseModel.swift
- Sikmogil/Model/ImageModel.swift
- Sikmogil/Model/UserProfile.swift
- Sikmogil/Services/Network/DietAPIManager.swift
- Sikmogil/Services/Network/ImageAPIManager.swift
- 식단 API, Model Update
- Sikmogil/Model/DietModel.swift : Model 구조체 정리
- Sikmogil/Services/Network/DietAPIManager.swift : API Manager
- Resolved: #33
> [Feat] 식단 API, Model Update

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Sikmogil/Services/Network/DietAPIManager.swift
- 누락된 파라미터, Package resolved 추가
이후 PR에서 패키지 충돌 날 수 있어서 충돌 생기면 저 불러주세요!
- Resolved: #40
> [Fix] add parameters & PackageConflict

- Sikmogil.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Sikmogil/Presentation/Diet/View/DietMainViewController.swift
- Sikmogil/Presentation/Diet/View/WaterBottomSheetViewController.swift
- Sikmogil/Presentation/Diet/ViewModel/DietViewModel.swift
- 물마시기 프로그래스바 뷰모델구현
- Presentation/Diet/ViewModel/DietViewModel 내용 추가
- waterLiterLabelTextPublisher/waterProgressPublisher
| 물마시기 입력 | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/161270633/5721d5c7-9c80-4468-a64c-446ad3c7a63c" width ="250">|
- Resolved: #
> [feat] 물마시기 프로그래스바 / 공복타이머 기능구현

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil/Presentation/Main/View/CalendarViewController.swift
- Sikmogil/Presentation/Main/View/DiaryRecordFloatingViewController.swift
- Sikmogil/Services/Network/DietAPIManager.swift
- Sikmogil/Services/Network/UserAPIManager.swift
- Sikmogil/Utills/Extensions/UIViewControllerExtension.swift
- Sikmogil/Utills/Helpers/FloatingPannelStyleHelper.swift
-  캘린더 패널 수정, API 코드 수정
Sikmogil/Presentation/Main/View/CalendarViewController.swift - 캘린더 일기 작성 패널 수정
Sikmogil/Presentation/Main/View/DiaryRecordFloatingViewController.swift - 작성 일기 내용 여부 탐색 + 키보드 하이딩 추가
Sikmogil/Services/Network/DietAPIManager.swift - 서버 수정에 따른 API 수정
Sikmogil/Services/Network/UserAPIManager.swift - 회원 정보 출력 함수 생성
Sikmogil/Utills/Helpers/FloatingPannelStyleHelper.swift - FloatingPannel customLayout
- Resolved: #42
> [Feat] 캘린더 패널 수정, API 코드 수정

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil/Presentation/Exercise/View/APITestViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseSelectionViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseTimerViewController.swift
- Sikmogil/Presentation/Exercise/View/StepsViewController.swift
- Sikmogil/Presentation/Exercise/ViewModel/ExerciseViewModel.swift
- Sikmogil/Resources/SikmogilPlist.plist
- Sikmogil/Services/Network/ExerciseAPIManager.swift
- Sikmogil/Services/Network/ExerciseCategoryAPIManager.swift
- Sikmogil/Utills/Extensions/Double.swift
- Sikmogil/Utills/Extensions/Extension.swift
- Sikmogil/Utills/Extensions/SikmogilBundle++.swift
- Sikmogil/Utills/Extensions/UILabel.swift
- 데이터 바인딩 위한 Exercise API 테스트 작업
- Exercise Category API
- 로직 설계 시작
- Exercise API Test 
- 공공 헬스케어 운동 API 추가 : ExerciseCategoryAPIManager
- 걸음 수 page :  데이터 화면에 업데이트 완료
- 운동 선택 page : 1차 로직 구현 완료 
- 버튼 활성화 및 데이터 업데이트
| 걸음 수 | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/129912074/8ce97d22-3846-4296-bdc8-416f3f6ee611" width ="250">|
| 운동 선택  | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/129912074/42a7e6b8-3d74-4a2d-89d2-ddc5ae21f68c" width ="250">|
- 운동 관련 API 는 전부 잘 되는 것 테스트했습니다.
- 공공 데이터 API키를 실수로 커밋해버린 점 양해부탁드립니다..! 최근 커밋엔 삭제하고 했습니다.
- 로직은 계속 수정할 예정입니다.
- Resolved: #32
> [Feat] Exercise API Test, 공공 헬스케어 운동 API 추가, 화면 로직

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil.xcodeproj/xcshareddata/xcschemes/Sikmogil.xcscheme
- Sikmogil/Model/CalendarModel.swift
- Sikmogil/Model/UserProfile.swift
- Sikmogil/Presentation/Main/View/CalendarCell.swift
- Sikmogil/Presentation/Main/View/CalendarViewController.swift
- Sikmogil/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
- Sikmogil/Services/Network/UserAPIManager.swift
- Custom Calendar
Develop Branch 겹치는 모델명으로 인해서 작업 중간에 PR올립니다
- Resolved: #42
> [Feat] Custom Calendar

- Sikmogil/Model/UserProfile.swift
- Sikmogil/Services/Network/UserAPIManager.swift
- User 정보 출력 모델 및 API Func 수정
기존 리스폰스 모델 수정으로 인한 변경 사항 추가
- Resolved: #42
> [Fix] User 정보 출력 모델 및 API Func 수정

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil/Application/AppDelegate.swift
- Sikmogil/Model/CalendarModel.swift
- Sikmogil/Model/TargetModel.swift
- Sikmogil/Presentation/Main/View/CalendarCell.swift
- Sikmogil/Presentation/Main/View/CalendarViewController.swift
- Sikmogil/Presentation/Main/View/DayViewController.swift
- Sikmogil/Presentation/Main/View/DiaryRecordFloatingViewController.swift
- Sikmogil/Presentation/Main/View/MainViewController.swift
- Sikmogil/Presentation/Main/View/WeightRecordFloatingViewController.swift
- Sikmogil/Presentation/Main/ViewModel/CalendarViewModel.swift
- Sikmogil/Presentation/Main/ViewModel/MainViewModel.swift
- Sikmogil/Services/Network/CalendarAPIManager.swift
- Sikmogil/Services/Network/LoginAPIManager.swift
- 캘린더, 목표화면 API 적용
| GIF | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/112539563/5fe9a2f6-4cc2-4ec1-9be3-da0a6b620ef1" width ="250">|
API, ViewModel Combine 사용해서 작업했습니다 in, output 정리 까지 하려면 시간이 너무 오래걸릴 것 같아서 이부분은 나중에 정리할게요
- Resolved: #42
> [Feat] 캘린더, 목표화면 API 적용

- Sikmogil/Application/SceneDelegate.swift
- Sikmogil/Model/UserProfile.swift
- Sikmogil/Presentation/Login/View/LoginViewController.swift
- Sikmogil/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
- Sikmogil/Services/Network/UserAPIManager.swift
- 온보딩시 섭취 가능 칼로리, 리마인드 타임 저장
- User Profile 수정
- 온보딩 정보 업데이트로 전부 로그인 처음부터 한번 하셔야해서 하실때 말씀해주세요
- Resolved: #56
> [Feat] User Onboarding 정보 업데이트

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil/Presentation/Exercise/View/APITestViewController.swift
- Sikmogil/Presentation/Exercise/View/Cell/ExerciseHistoryCell.swift
- Sikmogil/Presentation/Exercise/View/ExerciseResultViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseSelectionViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseTimerViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
- Sikmogil/Presentation/Exercise/ViewModel/ExerciseSelectionViewModel.swift
- Sikmogil/Presentation/Exercise/ViewModel/ExerciseViewModel.swift
- 화면 간 데이터 이동
- 데이터 API 저장 및 fetch
- 뷰모델 사용하여 리팩토링
| 측정 | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/129912074/579dfca6-3f8f-40eb-a36c-a7b96bab31c2" width ="250">|
| 기록 | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/129912074/3e8b4860-6842-459b-83b1-17ed268a57e0" width ="250">|
- API, ViewModel Combine 사용해서 작업했습니다 
- 뷰모델에서 변수를 옵져버블하게 적용하지 못해서 그 부분은 추후에 수정하겠습니다.
- 데이터 추가하기 후 상위 탭바로 이동하면 데이터가 업데이트 되어야 하는 문제를 해결하지 못해서 상단 탭 버튼인 운동 버튼을 한 번 눌러야 업데이트됩니다.
- Resolved: #50
> [Feat] 운동 데이터 로직 및 API 연결]

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil/Application/SceneDelegate.swift
- Sikmogil/Presentation/Diet/View/DietAPITest.swift
- Sikmogil/Presentation/Diet/View/DietMainViewController.swift
- Sikmogil/Presentation/Diet/View/WaterBottomSheetViewController.swift
- Sikmogil/Presentation/Diet/ViewModel/DietViewModel.swift
- Sikmogil/Presentation/Diet/ViewModel/WaterViewModel.swift
- Sikmogil/Presentation/Diet/ViewModel/addMealViewModel.swift
- Sikmogil/Resources/SikmogilPlist.plist
- Sikmogil/Services/Network/DietAPIManager.swift
- 식단 API연결
-  식단 API 테스트
-  식단 뷰모델 생성
-  식단 API 패치 구현 (물마시기까지)
-  식단 API 업로드 구현 (물마시기까지)
- Resolved: #
>  [Feat] 식단 API연결

- Sikmogil/Presentation/Main/View/MainViewController.swift
- Sikmogil/Presentation/Profile/View/ProfileViewController.swift
- 목표기간 성별 데이터 오류 수정
Sikmogil/Presentation/Main/View/MainViewController.swift => 목표기간 계산식, 첫가입시 몸무게 연동
Sikmogil/Presentation/Profile/View/ProfileViewController.swift => 성별 누락 수정
| GIF | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/112539563/9a64ddae-933b-4460-a68f-8039f7c68aad" width ="250">|
- Resolved: #
> [Fix] 목표기간 성별 데이터 오류 수정

- Sikmogil/Presentation/Exercise/View/StepsViewController.swift
- 걸음수 권한 승인 후 바로 UI 업데이트 되도록 수정
| GIF | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/129912074/21f0d432-3c97-41c0-81dc-495d58148e8f" width ="250">|
- 임시값으로  테스트 해봤습니다.
- Resolved: #93
> [Fix] 걸음수 업데이트 수정

- Sikmogil/Presentation/Main/View/MainViewController.swift
- 목표 화면 퍼센트 뷰, 스크롤 영역 수정
Sikmogil/Presentation/Main/View/MainViewController.swift => 퍼센트 뷰, 스크롤 영역 수정
퍼센트 뷰 20 퍼 이상일 때 보이게 수정했습니다
- Resolved: #
> [Fix] 목표 화면 퍼센트 뷰, 스크롤 영역 수정

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil/Presentation/Login/View/LoginViewController.swift
- Sikmogil/Presentation/Login/ViewModel/LoginViewModel.swift
- Sikmogil/Presentation/Onboarding/View/PermissionViewController.swift
- Sikmogil/Presentation/Profile/View/ProfileViewController.swift
- Sikmogil/Presentation/Splash/SplashViewController.swift
- Sikmogil/Services/Network/AuthInterceptor.swift
- Sikmogil/Services/Network/CalendarAPIManager.swift
- Sikmogil/Services/Network/DietAPIManager.swift
- Sikmogil/Services/Network/ExerciseAPIManager.swift
- Sikmogil/Services/Network/ImageAPIManager.swift
- Sikmogil/Services/Network/LoginAPIManager.swift
- Sikmogil/Services/Network/ProfileAPIManager.swift
- Sikmogil/Services/Network/UserAPIManager.swift
- Sikmogil/Services/PersistentStorage/TokenStorage.swift
- 화면 전환 에니메이션 수정, API RequestInspector 추가, 토큰 저장소 분리
RequestInspector
- Sikmogil/Services/Network/AuthInterceptor.swift
토큰 저장소 분리
- Sikmogil/Services/PersistentStorage/TokenStorage.swift
RequestInspector 적용
- Sikmogil/Services/
RequestInspector 저도 처음 알았는데 공부해보시면 좋을 것 같습니다
해당 PR은 배포에 포함해서 진행시키겠습니다
- Resolved: #99
> [Feat] 화면 전환 에니메이션 수정, API RequestInspector 추가, 토큰 저장소 분리

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil/Model/DietModel.swift
- Sikmogil/Model/SavedDietImage.swift
- Sikmogil/Presentation/Diet/Extensions/FloatingPanelControllerDelegate.swift
- Sikmogil/Presentation/Diet/View/Cell/BreakfastTableViewCell.swift
- Sikmogil/Presentation/Diet/View/Cell/DinnerTableViewCell.swift
- Sikmogil/Presentation/Diet/View/Cell/LunchTableViewCell.swift
- Sikmogil/Presentation/Diet/View/DietAlbumViewController.swift
- Sikmogil/Presentation/Diet/View/DietBottomSheetViewController.swift
- Sikmogil/Presentation/Diet/View/DietMainViewController.swift
- Sikmogil/Presentation/Diet/ViewModel/DietAlbumViewModel.swift
- Sikmogil/Presentation/Diet/ViewModel/addMealViewModel.swift
- Sikmogil/Services/Network/DietAPIManager.swift
- Sikmogil/Services/Network/ImageAPIManager.swift
- 식단 앨범 api 연결
- 다이어트 바텀시트 ui 수정
- 식단 앨범 뷰모델 유저디폴트 저장 -> api 연결로 수정했습니다.
- 다이어트 바텀시트 아이콘 크기 축소에 따라 뷰와 테이블뷰셀 ui를 수정했습니다.
| 앨범 GIF | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/161270633/830acb40-9b36-4af9-ae77-66b1388244de" width ="250">|
| 바텀시트 UI | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/161270633/e4fa3ba2-7faa-4d8b-ac8c-399d6b3ff731" width ="250">|
- Resolved: #95
> [Feat/Design] 식단 앨범 api 연결 / 다이어트 바텀시트 ui 수정

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil/Presentation/Diet/Extensions/FloatingPanelControllerDelegate.swift
- Sikmogil/Presentation/Diet/View/DietMainViewController.swift
- Sikmogil/Presentation/Main/View/MainViewController.swift
- Sikmogil/Presentation/Main/ViewModel/MainViewModel.swift
- Sikmogil/Services/Network/ImageAPIManager.swift
- 플로팅 패널, 목표기간 수정
- Resolved: #
> [Fix] 플로팅 패널, 목표기간 수정

- Sikmogil/Presentation/Diet/Extensions/FloatingPanelControllerDelegate.swift
- Sikmogil/Presentation/Main/View/MainViewController.swift
- Sikmogil/Presentation/Profile/View/GoalSettingsViewController.swift
- Sikmogil/Presentation/Profile/View/NotificationSettingsViewController.swift
- 목표 수정 화면 캘린더 선택 제한, 키보드 이벤트, 첫 가입시 체중 목표까지 오류수정
| GIF | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/112539563/cdd941c8-a7ba-442a-b5f8-c64ccf890924" width ="250">|
| GIF | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/112539563/ce60ccf6-70c8-4506-8fc2-856d0337ac26" width ="250">|
- Resolved: #105
> [Fix] 목표 수정 화면 캘린더 선택 제한, 키보드 이벤트, 첫 가입시 체중 목표까지 오류수정

- Sikmogil/Presentation/Exercise/View/StepsViewController.swift
- Sikmogil/Presentation/Main/View/MainViewController.swift
- Sikmogil/Presentation/Onboarding/View/PermissionViewController.swift
- 권한 동의 관련 내용 수정 
- 건강 최초 동의를 권한 동의 화면으로 이전하고 문구 추가했습니다
- Resolved: #108
> [Fix] 1차 리젝 내용 일부 수정

- Sikmogil/Presentation/Diet/View/DietMainViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseMenuViewController.swift
- Sikmogil/Presentation/Main/View/MainViewController.swift
- Sikmogil/Presentation/Onboarding/View/PrivacyPolicyViewController.swift
- Sikmogil/Presentation/Profile/View/ProfileViewController.swift
- Sikmogil/Presentation/Profile/View/SettingsViewController.swift
- Sikmogil/Presentation/Profile/View/SpandrelSettingsViewController.swift
- Sikmogil/Presentation/Splash/SplashViewController.swift
- Sikmogil/Presentation/TabBar/CustomNavigationController.swift
- Sikmogil/Resources/Info.plist
- Sikmogil/Services/Network/UserAPIManager.swift
- Sikmogil/Utills/Helpers/NotificationHelper.swift
- 권한 동의 텍스트 수정 및 건강 동의 화면 이동
- 회원 탈퇴 로직 구현
- 메인 뷰 텍스트 처리 조건 변경
- 목표, 다이어트, 운동, 마이페이지 헤더 위치 정렬
| GIF | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/112539563/b48fa547-f6d7-4dad-888c-d20facb727e0" width ="250">|
| GIF | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/112539563/5f6bf5d6-10c1-4b58-9efb-0d59c460dfdf" width ="250">|
| GIF | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/112539563/da85a6e6-469d-4259-a914-996b1db00916" width ="250">|
- Resolved: #108
> [Deploy] 1차 배포 리젝 사항 수정

- Sikmogil/Presentation/Onboarding/View/Step3ViewController.swift
- 최초 로그인 시 공복시간 14시간으로 설정
- Resolved: #
> [refactor] 최초 로그인 시 공복시간 14시간으로 설정

- Sikmogil/Presentation/Exercise/View/ExerciseAlbumViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseResultViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
- Sikmogil/Presentation/Exercise/View/PhotoSelectViewController.swift
- Sikmogil/Services/Network/ExerciseAPIManager.swift
- 사진 앨범 UI
- PhotoSelectViewController
| GIF | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/129912074/768886d4-127b-4512-bbd0-f1911b901ec1" width ="250">|
- Resolved: #111
> [Design] 사진 앨범 UI

- Sikmogil.xcodeproj/project.pbxproj
- Sikmogil/Presentation/Diet/View/Cell/DietAlbumCollectionViewCell.swift
- Sikmogil/Presentation/Diet/View/DietAlbumViewController.swift
- Sikmogil/Presentation/Diet/View/DietPhotoSelectViewController.swift
- 식단 앨범 상세보기, 삭제기능
- 사진 상세보기 및 삭제
- 롱프레스 터치 삭제
- 운동앨범과 디자인 통일 *파일형식이 데이터라 애니메이션 적용은 안됩니다!
| ui변경 | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/161270633/3d0b4bf1-34c3-4231-87b3-d774283a362a" width ="250">|
| 상세보기/삭제 | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/161270633/c94b6317-2d1e-4a6a-a74d-a766ca856735" width ="250">|
| 롱프레스삭제 | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/161270633/0d6863c2-f689-442e-bbf5-e24e5ea3fdeb" width ="250">|
애니메이션 적용안되는게 아쉬워서 이후에 시간생기면 방법을 찾아보겠습니다 🥺
- Resolved: #117
> [Feat] 식단 앨범 상세보기, 삭제기능

- Sikmogil.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Sikmogil/Presentation/Diet/View/Cell/BreakfastTableViewCell.swift
- Sikmogil/Presentation/Diet/View/DietAlbumViewController.swift
- Sikmogil/Presentation/Diet/View/DietBottomSheetViewController.swift
- Sikmogil/Presentation/Diet/View/DietMainViewController.swift
- Sikmogil/Presentation/Diet/View/WaterBottomSheetViewController.swift
- 식단 ui수정
+추가 타이틀과 서브타이틀간격 6으로 조정
+워터바텀시트 디자인변경
+롱프레스리액션 블락
- Resolved: #125
> [design] 식단 ui수정

- Sikmogil/Model/ExerciseModel.swift
- Sikmogil/Presentation/Exercise/View/ExerciseAlbumViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseMenuViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseResultViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseSelectionViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseTimerViewController.swift
- Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
- Sikmogil/Presentation/Exercise/View/PhotoSelectViewController.swift
- Sikmogil/Presentation/Exercise/View/StepsViewController.swift
- Sikmogil/Presentation/Exercise/ViewModel/ExerciseAlbumViewModel.swift
- Sikmogil/Presentation/Exercise/ViewModel/ExerciseViewModel.swift
- Sikmogil/Services/Network/ExerciseAPIManager.swift
- 앨범 사진 삭제
- 운동 추가 로직 오류 수정
- 로딩 애니메이션
- 뷰모델 수정
| 사진 삭제 | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/129912074/64562ddc-df98-4d57-ad35-bcde6785e285" width ="250">|
| 운동 추가 | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/129912074/21ca5445-501d-4fa1-9583-2844b2955936" width ="250">|
- Resolved: #111
> [Feat] 앨범 사진 삭제, [Fix] 운동 추가 로직 분리

- Sikmogil/Model/PostModel.swift
- Sikmogil/Presentation/Community/View/Board/View/WriteViewController.swift
- Sikmogil/Presentation/Community/View/Board/ViewModel/CreatePostViewModel.swift
- Sikmogil/Services/Network/BoardAPIManager.swift
- 이전 PR 누락 내용  추가 PR
- Resolved: #
> [Fix] 누락 내용 PR

- Sikmogil/Presentation/Exercise/View/ExerciseViewController.swift
- emptyLabel 업데이트
| GIF | <img src = "https://github.com/NBCampArchive/Sikmogil/assets/129912074/51409655-afd2-4f46-bb2c-2263a720b9f8" width ="250">|
- Resolved: #111
> [Fix] 테이블 뷰 라벨 Update 누락

- Sikmogil/Presentation/Main/View/DayViewController.swift
- Sikmogil/Presentation/Main/View/PhotoCell.swift
- Sikmogil/Presentation/Profile/View/EditProfileViewController.swift
- 캘린더 이미지로딩 수정, 중복코드 제거
- Resolved: #
> [Fix] 중복 코드 제거 및 이미지 로딩 통일
